### ISSUE TITLE
Blog Post: Installation of Jenkins & Simple job

### ISSUE THREAD

**Issue by Nehasingh1300** [StatusNeo/Hacktoberfest_2020#15]
Hi 
I am Neha Singh, Developer Evangelist at StatusNeo and also a student at UPES doing Btech in CS with a specialization in DevOps. I would like to contribute to this repository by writing a blog on "Installation of Jenkins & Simple job" and would like to share my knowledge. 
Thank You.

**Comment by NishkarshRaj** [comment]
Congrats! You created your first PR on this repository :+1: We will revert shortly' first issue

**Comment by NishkarshRaj** [comment]
@Nehasingh1300 always link your PR #14 like this in the issues.

It was an amazing effort.

One advise: Always add relative links in README rather than absolute links because they don't carry forward to the forked repositories. 👍

**Comment by Nehasingh1300** [comment]
Okay thanks
