### ISSUE TITLE
Blog Post: Kubernetes

### ISSUE THREAD

**Issue by whiskerwind** [StatusNeo/Hacktoberfest_2020#20]
Hi there, could I create a blog post about Kubernetes and it's use? I'm a complete novice but it sounds like a worthwhile thing to learn and research about.

**Comment by NishkarshRaj** [comment]
Congrats! You just created a PR :heart: The maintainers will review soon' first issue

**Comment by NishkarshRaj** [comment]
> 
> 
> Congrats! You just created a PR ❤️ The maintainers will review soon' first issue

Oh My god! This GitHub Actions is a pain 😭

**Comment by NishkarshRaj** [comment]
@whiskerwind go ahead! Write the blog and add your blog topic and link to your GitHub in the ReadME file. 👍
