### ISSUE TITLE
Blog | Introduction to makefiles

### ISSUE THREAD

**Issue by Maulikchhabra** [StatusNeo/Hacktoberfest_2020#48]

**Comment by Maulikchhabra** [comment]
I want to work on this issue!

**Comment by NishkarshRaj** [comment]
Congrats! You just created a PR :heart: The maintainers will review soon' first issue

**Comment by NishkarshRaj** [comment]
@Maulikchhabra create a PR 😄

**Comment by NishkarshRaj** [comment]
Merged in #53
